- config/redirects
JIRA:
https://jira.mongodb.org/browse/DOCSP-11755
Updated redirects file to default to 7.1 when "current" accessed.
> DOCSP-11755: update redirect to point to 7.1

- Makefile
Same situation as with docs-ruby and docs-php-library, please. 😁
> Update to publish to DOP-owned AWS buckets

- .gitmodules
- snooty.toml
- worker.sh
Important note: we have done **nothing** to handle the generation of the API docs using yarn. We will need to coordinate with the mongoid engineers to sort out a solution to the generation of those API docs since it doesn't really make sense for it to go through the Autobuilder / be part of this repo anymore.
Once this PR is merged, the master branch of docs-mongoid will be deployable using the /deploy command and build with snooty.
> DOP-3400: migrate build system to snooty :tada:

- Makefile
The staging site prefix currently points to the wrong url. This PR fixes the URL which allows anyone building with legacy tooling to get the correct staging url when running the stage target.
> Fix QA site prefix

- config/redirects
JIRA: https://jira.mongodb.org/browse/DOCSP-37022
Staging: https://preview-mongodbnorareidy.gatsbyjs.io/spark-connector/DOCSP-37022-fix-redirects/
Redirects:
Redirect 301 /docs/mongoid/current/release-notes/mongoid-7.0 https://www.mongodb.com/docs/mongoid/current/
> DOCSP-37022: Fix redirect

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-39124
Redirects:
Redirect 301 /docs/mongoid/ https://www.mongodb.com/docs/mongoid/current/
Redirect 301 /docs/mongoid/master https://www.mongodb.com/docs/mongoid/upcoming/
Redirect 301 /docs/mongoid/current/release-notes/mongoid-7.0 https://www.mongodb.com/docs/mongoid/current/
> DOCSP-39124: Use upcoming instead of master

- .gitignore
- source/release-notes/mongoid-8.0.txt
jira - <https://jira.mongodb.org/browse/DOCSP-42363>
staging - <https://preview-mongodbshuangela.gatsbyjs.io/mongoid/DOCSP-42363-new-caching-behavior/release-notes/mongoid-8.0/#new-caching-behavior-of--association-_ids-methods>
> [DOCSP-42363] Add New Caching Behavoir

- source/reference/compatibility.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43298
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-43298-rails-7.2/reference/compatibility/#rails-compatibility
> DOCSP-43298: Rails 7.2 compat

- .github/workflows/vale-tdbx.yml
- source/add-existing.txt
- source/index.txt
- source/quick-start-rails.txt
- source/quick-start-rails/download-and-install.txt
- source/quick-start-sinatra.txt
- source/reference/compatibility.txt
- source/reference/crud.txt
- source/reference/fields.txt
- source/tutorials/getting-started-rails6.txt
- source/tutorials/getting-started-rails7.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44647>
Staging - https://deploy-preview-55--docs-mongoid.netlify.app/add-existing/
> DOCSP-44647: add to existing app

- snooty.toml
- source/includes/interact-data/query.rb
- source/interact-data.txt
- source/interact-data/specify-query.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42753>
Staging - https://deploy-preview-58--docs-mongoid.netlify.app/interact-data/specify-query/
> DOCSP-42753: specify query part 1

- source/reference/compatibility.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45297
Staging - https://deploy-preview-64--docs-mongoid.netlify.app/reference/compatibility/
> DOCSP-45297: 9.0.3 and 8.1.7 release

- source/includes/interact-data/query.rb
- source/interact-data/modify-results.txt
- source/interact-data/specify-query.txt
- source/reference/fields.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44821>
Staging - Starts at https://deploy-preview-61--docs-mongoid.netlify.app/interact-data/specify-query/#element-match
> DOCSP-44821: specify a query pt 2

- source/data-modeling.txt
- source/data-modeling/inheritance.txt
- source/includes/data-modeling/inheritance.rb
JIRA - <https://jira.mongodb.org/browse/DOCSP-45330>
Staging - https://deploy-preview-66--docs-mongoid.netlify.app/data-modeling/inheritance/
> DOCSP-45330: inheritance

- snooty.toml
- source/data-modeling.txt
- source/data-modeling/documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45358>
Staging - https://deploy-preview-67--docs-mongoid.netlify.app/data-modeling/documents/
> DOCSP-45358: documents

- source/data-modeling.txt
- source/data-modeling/nested-attributes.txt
- source/includes/data-modeling/nested_attr.rb
JIRA - <https://jira.mongodb.org/browse/DOCSP-45360>
Staging - https://deploy-preview-71--docs-mongoid.netlify.app/data-modeling/nested-attributes/
> DOCSP-45360: nested attributes

- source/includes/interact-data/text-search.rb
- source/interact-data.txt
- source/interact-data/text-search.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45362>
Staging - https://deploy-preview-72--docs-mongoid.netlify.app/interact-data/text-search/
> DOCSP-45362: text search

- source/data-modeling.txt
- source/data-modeling/field-behaviors.txt
- source/includes/data-modeling/field-behaviors.rb
JIRA - https://jira.mongodb.org/browse/DOCSP-45436
Staging - https://deploy-preview-68--docs-mongoid.netlify.app/data-modeling/field-behaviors/
> DOCSP-45436 Field Behaviors page

- snooty.toml
- source/data-modeling.txt
- source/data-modeling/validation.txt
- source/includes/data-modeling/validation.rb
- source/interact-data.txt
- source/interact-data/nested-attributes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45363>
Staging - https://deploy-preview-73--docs-mongoid.netlify.app/data-modeling/validation/
> DOCSP-45363: validation

- snooty.toml
- source/configuration.txt
- source/configuration/sharding.txt
- source/data-relationships/associations.txt
- source/includes/configuration/sharding.rb
- source/index.txt
- source/reference/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45357
Staging - https://deploy-preview-76--docs-mongoid.netlify.app/configuration/sharding/
> DOCSP-45357 Sharding Configuration

- source/data-modeling/associations.txt
- source/includes/data-modeling/association-behaviors.rb
JIRA - https://jira.mongodb.org/browse/DOCSP-46072
Staging - https://deploy-preview-82--docs-mongoid.netlify.app/data-modeling/associations/#association-behaviors
> DOCSP-46072 Associations part 2

- source/includes/interact-data/crud.rb
- source/interact-data/crud.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46394>
Staging - https://deploy-preview-83--docs-mongoid.netlify.app/interact-data/crud/#dirty-tracking
> DOCSP-46394: CRUD remaining sections

- source/reference/associations.txt
Per server team, the $comment query operator support was dropped in v5.1, so this broken link can be deleted.
JIRA - <https://jira.mongodb.org/browse/DOCSP-46474>
Staging - <https://deploy-preview-85--docs-mongoid.netlify.app/reference/associations/>
> DOCSP-46474: Remove broken link to deprecated comment operator

- source/configuration.txt
- source/configuration/collection-config.txt
- source/includes/configuration/collection-config.rb
JIRA - https://jira.mongodb.org/browse/DOCSP-42743
Staging - https://deploy-preview-95--docs-mongoid.netlify.app/configuration/collection-config/
> DOCSP-42743 Collection config

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-47088>
```
Redirect 301 /docs/mongoid/v9.0/api/Mongoid/Errors/InvalidStorageParent.html https://www.mongodb.com/docs/mongoid/v9.0/api/ # resolve 404 for removed InvalidStorageParent class
Redirect 301 /docs/mongoid/master/api/Mongoid/Errors/InvalidStorageParent.html https://www.mongodb.com/docs/mongoid/master/api/ # resolve 404 for removed InvalidStorageParent class
Redirect 301 /docs/mongoid/v9.0/api/Post.html https://www.mongodb.com/docs/mongoid/v9.0/api/ # resolve 404 for removed entry
Redirect 301 /docs/mongoid/master/api/Post.html https://www.mongodb.com/docs/mongoid/master/api/ # resolve 404 for removed entry
```
> DOCSP-47088 API Internal 404s

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-46743>
The page doesn't seem to need to be accessible (https://www.mongodb.com/docs/mongoid/current/tutorials/), so I created a redirect instead of making the title longer.
No pages to preview
> DOCSP-46743 Too Short Titles: Tutorials redirect

- source/data-modeling/documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46744>
<li><a href=https://deploy-preview-111--docs-mongoid.netlify.app/data-modeling/documents>data-modeling/documents</a></li>
> DOCSP-46744 Too Short Titles: Document

- source/data-modeling/associations.txt
- source/interact-data/aggregation.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48435>
<li><a href=https://deploy-preview-116--docs-mongoid.netlify.app/data-modeling/associations>data-modeling/associations</a></li><li><a href=https://deploy-preview-116--docs-mongoid.netlify.app/interact-data/aggregation>interact-data/aggregation</a></li>
> DOCSP-48435: 404s

- source/data-modeling/indexes.txt
- source/includes/configuration/sample-config-options.yml
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48562>
- [app config](https://deploy-preview-117--docs-mongoid.netlify.app/configuration/app-config/#configuration-options:~:text=allow_duplicate_index_declarations%3A%20false)
- [indexes note](https://deploy-preview-117--docs-mongoid.netlify.app/data-modeling/indexes/#:~:text=NOTE-,Duplicate%20Indexes,-Mongoid%20might%20incorrectly)
- [whats new](https://deploy-preview-117--docs-mongoid.netlify.app/whats-new/#std-label-mongoid-version-9.1)
> DOCSP-48562: dupe index config

- source/includes/interact-data/modify-results.rb
- source/interact-data/modify-results.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44648>
- [raw results section](https://deploy-preview-118--docs-mongoid.netlify.app/interact-data/modify-results/#return-raw-data)
- [whats new](https://deploy-preview-118--docs-mongoid.netlify.app/whats-new/#what-s-new-in-9.1)
> DOCSP-44648: return raw results

- snooty.toml
- source/data-modeling/callbacks.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44703>
[content](https://deploy-preview-119--docs-mongoid.netlify.app/data-modeling/callbacks/#thread-local-variables)
[whats new](https://deploy-preview-119--docs-mongoid.netlify.app/whats-new/#get-and-set-thread-local-variables)
> DOCSP-44703: thread local variable getter/setter

- source/configuration/app-config.txt
- source/configuration/collection-config.txt
- source/configuration/forking-server-config.txt
- source/includes/configuration/sample-config-options.yml
- source/interact-data/query-cache.txt
- source/quick-start-rails.txt
- source/quick-start-sinatra.txt
- source/reference/compatibility.txt
- source/security/encryption.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46982>
<li><a href=https://deploy-preview-130--docs-mongoid.netlify.app/configuration/app-config>configuration/app-config</a></li><li><a href=https://deploy-preview-130--docs-mongoid.netlify.app/configuration/collection-config>configuration/collection-config</a></li><li><a href=https://deploy-preview-130--docs-mongoid.netlify.app/configuration/forking-server-config>configuration/forking-server-config</a></li><li><a href=https://deploy-preview-130--docs-mongoid.netlify.app/interact-data/query-cache>interact-data/query-cache</a></li><li><a href=https://deploy-preview-130--docs-mongoid.netlify.app/quick-start-rails>quick-start-rails</a></li><li><a …
> DOCSP-46982: update ruby driver links
