mongodb/docs-mongoid

conf.py
=> remove is_private theme which is causing errors in build

config/redirects
=> add redirects for 8.0

conf.py
=> DOCSP-30857: EOL v7.2

conf.py
=> DOCSP-30857: EOL v5.4

conf.py
=> DOCSP-30857: EOL v6.1

conf.py
=> DOCSP-30857: EOL v6.2

conf.py
=> DOCSP-30857: EOL v6.3

conf.py
=> DOCSP-30857: EOL v6.4

conf.py
=> DOCSP-30857: EOL v7.0

conf.py
=> DOCSP-30857: EOL v7.1

.gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37038/
=> DOCSP-37038: Fix links (staging)

.gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
=> DOCSP-37038: Broken links backport (staging)

.gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37327
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37327-staging/release-notes/mongoid-8.0/
=> DOCSP-37327: Fix table (staging)

.gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37327
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37327-backport/release-notes/mongoid-8.0/
=> DOCSP-37327: Fix table backport (staging)

source/reference/compatibility.txt
[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)
JIRA - https://jira.mongodb.org/browse/DOCSP-42092
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/mongoid/DOCSP-42092-add-v8-compatibility/reference/compatibility/#mongodb-server-compatibility
- [] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
=> DOCSP-42092 Add v8 to the compatibility table

source/release-notes/mongoid-8.0.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42363
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-42363-caching-code-examples/release-notes/mongoid-8.0/
=> DOCSP-42363: Add association_ids code examples

source/reference/aggregation.txt
=> Fix typo "aggragegate"

.github/workflows/vale-tdbx.yml, source/index.txt, source/interact-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42745>
Staging - https://deploy-preview-56--docs-mongoid.netlify.app/interact-data/
=> DOCSP-42745: interact with data

source/data-modeling.txt, source/index.txt, source/interact-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45306>
Staging - https://deploy-preview-65--docs-mongoid.netlify.app/data-modeling/
=> DOCSP-45306: model data drawer

source/contributing.txt, source/index.txt, source/installation-configuration.txt, source/release-notes.txt, source/schema-configuration.txt, source/tutorials.txt, source/working-with-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44946>
Staging - <https://deploy-preview-62--docs-mongoid.netlify.app/>
=> DOCSP-44946 TOC Relabel

config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-46957
No pages to preview
=> Add redirects for broken API URLs

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46735>
<li><a href=https://deploy-preview-103--docs-mongoid.netlify.app/index>index</a></li>
=> DOCSP-46735 Too Short Title: Mongoid

source/integrations-tools/external-resources.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46737>
<li><a href=https://deploy-preview-104--docs-mongoid.netlify.app/integrations-tools/external-resources>integrations-tools/external-resources</a></li>
=> DOCSP-46737 Too Short Title: Resources

source/data-modeling/callbacks.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46740>
<li><a href=https://deploy-preview-105--docs-mongoid.netlify.app/data-modeling/callbacks>data-modeling/callbacks</a></li>
=> DOCSP-46740 Too Short Title: Callbacks

source/interact-data/specify-query.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46741>
<li><a href=https://deploy-preview-109--docs-mongoid.netlify.app/interact-data/specify-query>interact-data/specify-query</a></li>
=> DOCSP-46741 Too Short Title: Query

source/quick-start-rails.txt, source/quick-start-rails/configure-mongodb.txt, source/quick-start-rails/create-a-connection-string.txt, source/quick-start-rails/create-a-deployment.txt, source/quick-start-rails/download-and-install.txt, source/quick-start-rails/next-steps.txt, source/quick-start-rails/view-data.txt, source/quick-start-rails/write-data.txt, source/quick-start-sinatra.txt, source/quick-start-sinatra/configure-mongodb.txt, source/quick-start-sinatra/create-a-connection-string.txt, source/quick-start-sinatra/create-a-deployment.txt, source/quick-start-sinatra/download-and-install.txt, source/quick-start-sinatra/next-steps.txt, source/quick-start-sinatra/view-data.txt, source/quick-start-sinatra/write-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48227>
<li><a href=https://deploy-preview-115--docs-mongoid.netlify.app/quick-start-rails>quick-start-rails</a></li><li><a href=https://deploy-preview-115--docs-mongoid.netlify.app/quick-start-rails/configure-mongodb>quick-start-rails/configure-mongodb</a></li><li><a href=https://deploy-preview-115--docs-mongoid.netlify.app/quick-start-rails/create-a-connection-string>quick-start-rails/create-a-connection-string</a></li><li><a href=https://deploy-preview-115--docs-mongoid.netlify.app/quick-start-rails/create-a-deployment>quick-start-rails/create-a-deployment</a></li><li><a href=https://deploy-preview-115--docs-mongoid.netlify.app/quick-start-rails/downlo …
=> DOCSP-48227: duplicate titles in QS

source/interact-data/transaction.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48976>
[transactions](https://deploy-preview-120--docs-mongoid.netlify.app/interact-data/transaction/)
=> DOCSP-48976: fix links

config/redirects
=> Redirect for master branch

source/security.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51303>
<li><a href=https://deploy-preview-135--docs-mongoid.netlify.app/security>security</a></li>
=> DOCSP-51303 Add noindex on security landing page
